name: apitest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_slider_drawer: ^2.1.3
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  geolocator: ^12.0.0
  flutter_spinkit: ^5.2.0
  weather_icons: ^2.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7  # 📸 Gallery aur Camera ke liye add kiya
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
